In [2]:
import numpy as np

- Tips for getting the most out of the course:
1. Consider your learning pace, as it varies for different individuals.
2. Emphasize the importance of practice, including quizzes, exercises, and following along with topics.
3. Acknowledge the challenge of completing a course and suggest starting small but being consistent with daily time commitments.
4. Highlight the enjoyment of learning and its positive impact on understanding complex topics.
5. Stress the importance of clarity on why you are taking the course, whether for a career change, data science, skill improvement, or other reasons.
6. Encourage revisiting your motivation during moments of low motivation to stay focused.
7. Emphasize the long-term benefits of expanding knowledge for personal and career advancement.
8. Conclude by expressing motivation and transitioning into the study of statistics.

## Descriptive Statistics

- Descriptive Statistics involves using measures to describe key features of data.
- The example given is a dataset with around 1000 records of people's heights.
|Height (in cm)|
|--------------|
|171           |
|171           |
|164           |
|175           |
|171           |
|168           |
|170           |


## What is a typical height?
    - The average height can be calculated.
    - What is the most common value?

In [1]:
# Findding the Mean, Median, Mode
# The mean is the average of all numbers. This code calculates Mean or Average of a list containing numbers: 

n_num = [171,171,164,175,171,168,170]
n = len(n_num)

get_sum = sum(n_num)
mean = get_sum / n

print("Mean / Average is: " + str(mean))

Mean / Average is: 170.0


# How to find the mean?

- Arrange the numbers in order from least to greatest.
    - Example: (1,3,2,6,7)
    - In order: (1,2,3,6,7)
    - The middle numbe is "3"
 
- If the numbers are not even.. the two middle numbers must be added and then divided.
    - Exmaple: (1,1,2,3,6,7,8,9)
    - The muddle numbes (3 and 6)
    - Add both (9) then divide by 2 which equals 4.5

In [8]:
n = [5,8,7,2,9]
np.median(n)

7.0

In [9]:
n_sorted=np.sort(n)
print(n_sorted)

[2 5 7 8 9]


In [10]:
length=len(n)
print(length)

5


In [11]:
length//2

2

In [12]:
n_sorted[length//2]

7

In [13]:
n[0]

5

In [14]:
n[2]

7

In [17]:
n=np.random.randint(0,15,9)
n

array([ 5, 10,  6,  5,  7, 14,  4,  0,  6])

In [18]:
n_sorted=np.sort(n)
n_sorted

array([ 0,  4,  5,  5,  6,  6,  7, 10, 14])

In [19]:
np.median(n)

6.0

In [21]:
len(n)//2

4

In [20]:
n_sorted[len(n)//2]

6

In [23]:
11//2

5

In [24]:
27//2

13

In [26]:
n=np.random.randint(0,20,10)
n

array([14,  1, 15, 14, 11,  1, 17, 18,  2, 15])

In [27]:
n_sorted=np.sort(n)
n_sorted

array([ 1,  1,  2, 11, 14, 14, 15, 15, 17, 18])

In [29]:
np.median(n)

14.0

In [31]:
middle=len(n)//2
middle

5

In [32]:
(n_sorted[middle-1]+n_sorted[middle])/2

14.0

In [36]:
def mymedianfunction(n):
    length=len(n)
    n_sorted=np.sort(n)
    middle=len(n)//2
    if length%2==0:
        
        m=(n_sorted[middle-1]+n_sorted[middle])/2
    else:
        m=n_sorted[middle]
    
    return m

In [39]:
n=[5,8,7,2,9]
mymedianfunction(n),np.median(n)

(7, 7.0)

In [40]:
n=[5,8,7,2,9,8]
mymedianfunction(n),np.median(n)

(7.5, 7.5)

In [41]:
3%2

1

In [42]:
5%2

1

In [43]:
6%2

0